import { Tenant } from 'src/tenant/tenant.entity';
import {
  Column,
  Entity,
  OneToMany,
  ManyToOne,
  RelationId,
  Unique,
} from 'typeorm';
import { ProductVariant } from './product-variant.entity';
import { AuditableEntity } from 'src/common/entity/auditable-base.entity';
import { Supplier } from 'src/supplier/supplier.entity';

@Entity({ name: 'products' })
@Unique(['tenant', 'sku'])   // aynı tenant içinde sku unique
@Unique(['tenant', 'name'])  // istersen name'i de unique yapabilirsin
export class Product extends AuditableEntity {

  @ManyToOne(() => Tenant, (tenant) => tenant.id, { eager: true })
  tenant: Tenant;

  @Column()
  name: string;

  @Column({ nullable: true })
  sku?: string; // internal code

  @Column({ nullable: true })
  description?: string;

  @Column({ nullable: true })
  image?: string;

  // 🔹 Fiyat alanları
  @Column({ type: 'varchar', length: 3, default: 'TRY' })
  defaultCurrency: string;

  @Column({ type: 'numeric', nullable: true })
  defaultSalePrice?: number | null; // KDV hariç veya dahil – projede nasıl karar verirsek

  @Column({ type: 'numeric', nullable: true })
  defaultPurchasePrice?: number | null; // tedarik alış fiyatı (opsiyonel)

  @Column({ type: 'numeric', nullable: true })
  defaultTaxPercent?: number | null; // ör: 20 => %20 KDV

  @Column({ type: 'numeric', nullable: true })
  defaultDiscountPercent?: number | null;

  @Column({ type: 'numeric', nullable: true })
  defaultDiscountAmount?: number | null;

  @Column({ type: 'numeric', nullable: true })
  defaultTaxAmount?: number | null;

  @Column({ type: 'numeric', nullable: true })
  defaultLineTotal?: number | null;

  /* @Column({ nullable: true })
  additionalImages?: string[]; */

  @Column({ default: true })
  isActive: boolean;

  @ManyToOne(() => Supplier, { nullable: true, eager: false, onDelete: 'SET NULL' })
  supplier?: Supplier | null;

  // RelationId mapping for API responses (DB column is generated by TypeORM relation).
  @RelationId((product: Product) => product.supplier)
  supplierId?: string | null;

  @OneToMany(() => ProductVariant, (variant) => variant.product)
  variants: ProductVariant[];

  // Relation count mapping için alan (DB sütunu değil)
  variantCount?: number;
}
